appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AajKMJKWJuDi0fBNzx4b8cRvgi6MmoXwnT80CfUDpZvcGIfBWoKkWoi01pRKsFS/WwmMe0jO7vLKi7WdhRPxv/+O3qRHTFXQAfUWYxc1ffCpwT9oHOnIF9wLUDn7lMm+Vhxw3GbJt2oWlg2sEf0kz716QOpxCAHCZV5K3+9/CzhQszOvk6iaq0nm7GRFNrRLsv5wyan1J87B3BWjmzlzfAHsHUGZF6s5lpP7t0MO4AlBOajCFLZmV5Ty2zICJrCcYRH8B/aLnqzUq4L8mZs85JsJcG1yDz8geDq6af8uaSzNjTv4woVDO3rf5vPmjfnr6vqG+zpmuRscdRZTFtSBnjsXcLr/ddAl06rBU1fNDCqe+A4uQ3H1kNGkHiq3MkGSd6kvMEfnSqxc++5QeSnb7ZpoHZDnhvVJztC6AGhbiUF7IMama8BKdwe0Z24ZYSWqjXQatgzQIAJ//rGwP/hRKYEqtgSUrKJhe/L7MKDM12N5gn/H2KXN6sX5tZ0MM3nsW+E+UDxJL0l+0qiM/l/WVxtnhS54bV7e4C0RoImnU2802Dr0EaduYKZzJQgL9Q6WQEvig5LIqF6vvMx+bqZJZ3IrwuZq+fGJcSUS+DyTAFJkIh70wbwZTzJ7CKuhoAtxEaBUf5PC2PcbVDKxruR9Vs7BwD8QUeVS9EbGheubx/0=
